### ISSUE TITLE
Documentation: sandbox buyer/seller account

### ISSUE THREAD

**Issue by anentropic** [django-oscar/django-oscar-paypal#102]
http://django-oscar-paypal.readthedocs.org/en/latest/express.html#getting-started

> You need to create a PayPal sandbox account which is different from your normal paypal account then use this account to create two ‘test’ users: a buyer and a seller. Once the seller is created, you will have access to a username, password and ‘signature’ which are used to authenticate API requests.
> 
> Add the following settings using the details from your sandbox buyer account:

...shouldn't that last line say "from your sandbox seller account" ?

**Comment by anentropic** [comment]
Also, when I login to PayPal developer site to set up sandbox accounts I see this:

![screen shot 2015-06-20 at 16 28 52](https://cloud.githubusercontent.com/assets/147840/8267930/78d49bd6-176a-11e5-9e46-c7d3b5122cbb.png)

does this project use the REST API or the Classic API?  Docs should say

I'm assuming I have to create an app before I can see API credentials for my sandbox accounts

**Comment by anentropic** [comment]
okay looking through the source it is Classic API

**Comment by maikhoepfel** [comment]
You're correct. And a PR to update the docs is much welcome :)

**Comment by sasha0** [comment]
Fixed by #215, thanks for @daniel-butler .
