### ISSUE TITLE
Wrong parameters passed to Applicator with Oscar 1.1

### ISSUE THREAD

**Issue by sasha0** [django-oscar/django-oscar-paypal#104]
In the recent Oscar version 1.1, Applicator expects next parameters - basket, user, request:    
```
class Applicator(object):

    def apply(self, basket, user=None, request=None):
```
Per https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/offer/applicator.py#L19.    
However, Applicator in `django-oscar-paypal` sends:    
```
# Re-apply any offers
        Applicator().apply(basket, self.request.user, self.request)
```
Per https://github.com/sasha0/django-oscar-paypal/blob/master/paypal/express/views.py#L228

**Comment by fjsj** [comment]
bump!

**Comment by feado** [comment]
thanks! it works!

**Comment by maikhoepfel** [comment]
Merging #101 should've fixed this. Thanks for the good issue report.
