### ISSUE TITLE
SuccessResponseView overrides the chosen shipping method

### ISSUE THREAD

**Issue by anentropic** [django-oscar/django-oscar-paypal#106]
I have been tracking down why my orders come through with the wrong shipping method code, but correct method name.

It's because in express checkout we have this code:

```python
    def get_shipping_method(self, basket, shipping_address=None, **kwargs):
        """
        Return the shipping method used
        """
        if not basket.is_shipping_required():
            return NoShippingRequired()

        # Instantiate a new FixedPrice shipping method instance
        charge_incl_tax = D(self.txn.value('PAYMENTREQUEST_0_SHIPPINGAMT'))

        # Assume no tax for now
        charge_excl_tax = charge_incl_tax
        method = FixedPrice(charge_excl_tax, charge_incl_tax)
        name = self.txn.value('SHIPPINGOPTIONNAME')

        if not name:
            session_method = super(SuccessResponseView, self).get_shipping_method(
                basket, shipping_address, **kwargs)
            if session_method:
                method.name = session_method.name
        else:
            method.name = name
        return method
```

Is there a reason we don't attempt to use the real shipping method class and instead instantiate a `FixedPrice` and set attributes on it?  Is this deliberately to avoid recalculating the price?  We have the basket object here and in `build_submission` method, can we not trust the real shipping method object to calculate the same price again?

If we're going to do it like above it should also set the `code` attribute at least

**Comment by maikhoepfel** [comment]
Closed by #107. Thank you for the great analysis and PR.
