### ISSUE TITLE
Paypal Express Error

### ISSUE THREAD

**Issue by d0zrisnot** [django-oscar/django-oscar-paypal#111]
Hey, I'm getting an error whenever I go through the paypal express transaction. Right after I click continue from the paypal page, I get redirected to the request url below and run into an error.

Request Method:	GET
Request URL:	http://127.0.0.1:8000/checkout/paypal/preview/2/?token=EC-93093849XG990420G&PayerID=F2LVL79XXMSS4
Django Version:	1.8.3
Exception Type:	AttributeError
Exception Value:	
'WSGIRequest' object has no attribute 'id'
Exception Location:	/Users/kura/Knightly/oscar_project/oscar/apps/offer/applicator.py in get_basket_offers, line 94
Python Executable:	/Users/kura/.virtualenvs/oscar_project/bin/python
Python Version:	2.7.10
Python Path:	
['/Users/kura/Knightly/oscar_project',
 '/Users/kura/.virtualenvs/oscar_project/lib/python27.zip',
 '/Users/kura/.virtualenvs/oscar_project/lib/python2.7',
 '/Users/kura/.virtualenvs/oscar_project/lib/python2.7/plat-darwin',
 '/Users/kura/.virtualenvs/oscar_project/lib/python2.7/plat-mac',
 '/Users/kura/.virtualenvs/oscar_project/lib/python2.7/plat-mac/lib-scriptpackages',
 '/Users/kura/.virtualenvs/oscar_project/lib/python2.7/lib-tk',
 '/Users/kura/.virtualenvs/oscar_project/lib/python2.7/lib-old',
 '/Users/kura/.virtualenvs/oscar_project/lib/python2.7/lib-dynload',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages',
 '/Users/kura/.virtualenvs/oscar_project/lib/python2.7/site-packages']
Server time:	Fri, 18 Sep 2015 16:20:12 +0800

**Comment by d0zrisnot** [comment]
Some additional information

/Users/kura/Knightly/oscar_project/oscar/apps/offer/applicator.py in get_basket_offers
    def get_basket_offers(self, basket, user):
        """
        Return basket-linked offers such as those associated with a voucher
        code
        """
        offers = []
                    if not basket.id or not user: ...
            return offers
        for voucher in basket.vouchers.all():
            available_to_user, __ = voucher.is_available_to_user(user=user)
            if voucher.is_active() and available_to_user:
                basket_offers = voucher.offers.all()

**Comment by tmiller02** [comment]
It looks like this is the same as issue #104. Since Applicator.apply() is using an outdated call signature in this project, it is passing the `request` to the `get_basket_offers` method rather than the `basket`
