### ISSUE TITLE
Travis "Python 3" environments really build with Python 2.7

### ISSUE THREAD

**Issue by fghaas** [django-oscar/django-oscar-paypal#124]
Case in point: https://travis-ci.org/django-oscar/django-oscar-paypal/jobs/101483297

That's a job that ostensibly runs in a Python 3.3 environment. From the build log:

```
$ export TOX_ENV=py33-django17-oscar10
0.00s$ source ~/virtualenv/python2.7/bin/activate
$ python --version
Python 2.7.9
```

That doesn't look right.

**Comment by fghaas** [comment]
@maikhoepfel, while you're fixing test runs, you may want to look into this one as well.

We're using tox-travis for this; see hastexo/django-oscar-vat_moss@bb6c8a529218b86012eeab163bddf2b8dfffbcc9. Slightly different approach, but at least it ensures that Python 3.3 and Python 3.4 envs do what it says on the tin.

**Comment by maikhoepfel** [comment]
@fghaas The Travis environment is indeed run with Python 2.7 if no version is specified. But tox creates individual virtual environments with the given Python version. Rest assured that they're run with the specified Python version. I just double-checked with updating my `tox.ini` to this:
```
[testenv]
commands = python --version
```

Thank you for the link to tox-travis. I prefer the simpler, albeit more verbose syntax over adding another library to learn about.
