### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by pahaz** [django-oscar/django-oscar-paypal#135]

**Comment by ddiazpinto** [comment]
I wonder the same question...

**Comment by scaryclam** [comment]
You might get a swifter answer on the django oscar google group https://groups.google.com/forum/#!forum/django-oscar as I'm not sure anyone is monitoring this repository frequently

**Comment by SalahAdDin** [comment]
I think so, no one release version since January, and `django-oscar`, well, slow development. And the mailing list, poor, i leave a question five days ago, and until now i haven't answer.

**Comment by fghaas** [comment]
Tagging a few people here who made the most recent merges: @sasha0 @vdboor @maikhoepfel, would you mind letting people know what your plans are about the future of this repository?

**Comment by SalahAdDin** [comment]
And it will be good if they can help us with other third party packages.

**Comment by solarissmoke** [comment]
Looks like nobody who wrote this code is still using it. I have put some time into making it Django 1.11 compatible in #159, but new features are unlikely to be added unless someone makes a PR.

**Comment by sasha0** [comment]
@fghaas Hi Florian. I'm not actively using application currently, but will try to dedicate some time to review existing pull requests. Thanks.

**Comment by fghaas** [comment]
Thanks @sasha0!
