### ISSUE TITLE
Templates try to load `url` from `future`, which causes error in Django 1.9

### ISSUE THREAD

**Issue by shnela** [django-oscar/django-oscar-paypal#151]
I'm using  `Django==1.9.10`, so I'm getting such errors.

> TemplateSyntaxError at /checkout/paypal/preview/2/
> 'url' is not a valid tag or filter in tag library 'future'

All because of `{% load url from future %}` line e.g. [here](https://github.com/django-oscar/django-oscar-paypal/blob/master/paypal/templates/paypal/express/preview.html#L4) and [here](https://github.com/django-oscar/django-oscar-paypal/blob/master/paypal/templates/paypal/express/dashboard/transaction_list.html#L4).

Do you intend to remove those lines according to [stackoverflow](http://stackoverflow.com/a/35179880/1565454)?

Edit: I'm using `django-oscar-paypal==0.9.7`.

**Comment by cmwaura** [comment]
Yeah I came across this error too and found the easy solution was to override the templates in my own template folder. So i just forked the project from my lib and added it to my template folder and just deleted the line on express and payflow templates. It's a tad hacky but it works.

**Comment by artforlife** [comment]
This is due to deprecated template tags. If you look in Pull Request section of this repository, you will find that the contributions to fix it have been sitting there for a long time. The same is true of all other `django-oscar-*` modules. For some reason, the owners of this project seem VERY slow, if at all, at accepting incoming changes.

**Comment by cmwaura** [comment]
i think that this particular project was actually abandoned.. There seems to be no additions and any sorta improvements around it.

**Comment by solarissmoke** [comment]
I've addressed this and other issues in  #159.

**Comment by cmwaura** [comment]
@solarissmoke  thanks man this will be of great help.. cheers
