### ISSUE TITLE
Current release version (0.9.7) does not match repo version (0.10)

### ISSUE THREAD

**Issue by andirigible** [django-oscar/django-oscar-paypal#160]
Hey, folks. This repo says its version is 0.10, but the latest release is 0.9.7. This is an issue because pip can't find 0.10 and therefore installs the latest version of Django (2.0), which is listed in the dependencies for 0.9.7 (`django>=1.11`). The dependencies in `setup.py` for the repo version (0.10) include `django>=1.11,<2`, so it appears this behavior isn't intentional.

Not a super pressing issue, but should probably be fixed for sanity's sake.

**Comment by solarissmoke** [comment]
The version on the master branch has been updated in anticipation of a new release. 

This should not have any bearing on what happens if you install from pypi though. What command are you using to install it?

**Comment by andirigible** [comment]
I used `pip install django-oscar-paypal` to install.

**Comment by solarissmoke** [comment]
This is fixed in https://github.com/django-oscar/django-oscar-paypal/commit/3bab7a17715b86583095beaa77f213977ceb3c0b and will take effect when the next version is released on pypi.
