### ISSUE TITLE
ImportError: cannot import name 'Application'

### ISSUE THREAD

**Issue by TCBCareTeam** [django-oscar/django-oscar-paypal#174]
Hey, I tried to integrate with django 2.2.5 and django oscar  django-oscar 2.0.2.  I am getting this error.  

 from paypal.express.dashboard.app import application as paypal_app
  File "/usr/local/app/pambo/oscar/local/lib/python3.6/dist-packages/django_oscar_paypal-1.0.0-py3.6.egg/paypal/express/dashboard/app.py", line 3, in <module>
    from oscar.core.application import Application

**Comment by solarissmoke** [comment]
This package is not yet compatible with Oscar 2 - hence the error. You will need to use Oscar 1.6. If anybody is able to spend a bit of time upgrading this package to support 2.0 I'm happy to review (don't have time myself to upgrade it at the moment).

**Comment by solarissmoke** [comment]
Fixed in #176.
