### ISSUE TITLE
Any plan to upgrade to nvp to new api?

### ISSUE THREAD

**Issue by jk7g14** [django-oscar/django-oscar-paypal#188]
I'm really happy to use oscar-paypal, but I've just found that nvp api is deprecated. 

I just wonder that there is any plan to upgrade this nvp api to a new rest api, if not I may consider to upgrade.

**Comment by sasha0** [comment]
Yes. Me and @samitnuk currently working on this, although we can't predict when it'd be finished.

**Comment by jk7g14** [comment]
That's great! Thanks for the notice!

**Comment by woutdp** [comment]
Any update on this? I'm interested in this as well: https://developer.paypal.com/docs/api/overview/

**Comment by samitnuk** [comment]
@woutdp 

If I understood you correctly, this is already implemented - please see [express_checkout folder](https://github.com/django-oscar/django-oscar-paypal/tree/master/paypal/express_checkout) and sandbox.

**Comment by woutdp** [comment]
@samitnuk 
Thanks! This is what I was looking for.

Semi related, for the REST api I found an issue when the product doesn't require shipping, but could be on my end. I'll submit a PR if I think I can fix it.

**Comment by samitnuk** [comment]
@woutdp 

> Semi related, for the REST api I found an issue when the product doesn't require shipping, but could be on my end. I'll submit a PR if I think I can fix it.

Could you please explain this in more detail (or maybe create an issue for this)?

**Comment by woutdp** [comment]
@samitnuk 
I've created a PR with the issues I was experiencing: https://github.com/django-oscar/django-oscar-paypal/pull/270
