### ISSUE TITLE
LookupError: No installed app with label 'communication'.

### ISSUE THREAD

**Issue by appleyuchi** [django-oscar/django-oscar-paypal#204]
I do the following steps:
`git clone https://github.com/django-oscar/django-oscar-paypal`
`cd django-oscar-paypal`
`make sandbox`
Then I get:

(python3.7) appleyuchi@ubuntu19:django-oscar-paypal$ make sandbox
pip install -r requirements.txt
Looking in indexes: https://pypi.douban.com/simple
Requirement already satisfied: django-oscar<2.1,>=2.0 in /home/appleyuchi/桌面/原始的Django-oscar/django-oscar/src (from -r requirements.txt (line 2)) (2.0.1)
Requirement already satisfied: coverage==5.0.3 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (5.0.3)
Requirement already satisfied: django-webtest==1.9.7 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from -r requirements.txt (line 4)) (1.9.7)
Requirement already satisfied: tox==3.14.5 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from -r requirements.txt (line 5)) (3.14.5)
Requirement already satisfied: pytest-django==3.8.0 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from -r requirements.txt (line 6)) (3.8.0)
Requirement already satisfied: pytest-cov==2.8.1 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from -r requirements.txt (line 7)) (2.8.1)
Requirement already satisfied: django-widget-tweaks==1.4.5 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from -r requirements.txt (line 8)) (1.4.5)
Requirement already satisfied: sorl-thumbnail==12.6.3 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from -r requirements.txt (line 9)) (12.6.3)
Requirement already satisfied: django-extensions==2.2.8 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from -r requirements.txt (line 12)) (2.2.8)
Requirement already satisfied: django-debug-toolbar==2.2 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from -r requirements.txt (line 13)) (2.2)
Requirement already satisfied: flake8 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from -r requirements.txt (line 14)) (3.7.9)
Requirement already satisfied: isort in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from -r requirements.txt (line 15)) (4.3.21)
Requirement already satisfied: django<3.1,>=2.2 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from django-oscar<2.1,>=2.0->-r requirements.txt (line 2)) (2.2.10)
Requirement already satisfied: pillow>=6.0 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from django-oscar<2.1,>=2.0->-r requirements.txt (line 2)) (7.0.0)
Requirement already satisfied: django-extra-views<0.14,>=0.13 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from django-oscar<2.1,>=2.0->-r requirements.txt (line 2)) (0.13.0)
Requirement already satisfied: django-haystack>=3.0b1 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from django-oscar<2.1,>=2.0->-r requirements.txt (line 2)) (3.0b1)
Requirement already satisfied: django-treebeard>=4.3.0 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from django-oscar<2.1,>=2.0->-r requirements.txt (line 2)) (4.3.1)
Requirement already satisfied: Babel<3.0,>=1.0 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from django-oscar<2.1,>=2.0->-r requirements.txt (line 2)) (2.8.0)
Requirement already satisfied: purl>=0.7 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from django-oscar<2.1,>=2.0->-r requirements.txt (line 2)) (1.5)
Requirement already satisfied: phonenumbers in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from django-oscar<2.1,>=2.0->-r requirements.txt (line 2)) (8.11.3)
Requirement already satisfied: django-phonenumber-field<4.0.0,>=3.0.0 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from django-oscar<2.1,>=2.0->-r requirements.txt (line 2)) (3.0.1)
Requirement already satisfied: factory-boy<3.0,>=2.4.1 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from django-oscar<2.1,>=2.0->-r requirements.txt (line 2)) (2.12.0)
Requirement already satisfied: django-tables2<2.3,>=2.2 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from django-oscar<2.1,>=2.0->-r requirements.txt (line 2)) (2.2.1)
Requirement already satisfied: webtest>=1.3.3 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from django-webtest==1.9.7->-r requirements.txt (line 4)) (2.0.34)
Requirement already satisfied: six<2,>=1.14.0 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from tox==3.14.5->-r requirements.txt (line 5)) (1.14.0)
Requirement already satisfied: py<2,>=1.4.17 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from tox==3.14.5->-r requirements.txt (line 5)) (1.8.1)
Requirement already satisfied: virtualenv>=16.0.0 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from tox==3.14.5->-r requirements.txt (line 5)) (20.0.7)
Requirement already satisfied: pluggy<1,>=0.12.0 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from tox==3.14.5->-r requirements.txt (line 5)) (0.13.1)
Requirement already satisfied: packaging>=14 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from tox==3.14.5->-r requirements.txt (line 5)) (20.1)
Requirement already satisfied: importlib-metadata<2,>=0.12; python_version < "3.8" in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from tox==3.14.5->-r requirements.txt (line 5)) (1.5.0)
Requirement already satisfied: filelock<4,>=3.0.0 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from tox==3.14.5->-r requirements.txt (line 5)) (3.0.12)
Requirement already satisfied: toml>=0.9.4 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from tox==3.14.5->-r requirements.txt (line 5)) (0.10.0)
Requirement already satisfied: pytest>=3.6 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from pytest-django==3.8.0->-r requirements.txt (line 6)) (5.3.5)
Requirement already satisfied: sqlparse>=0.2.0 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from django-debug-toolbar==2.2->-r requirements.txt (line 13)) (0.3.0)
Requirement already satisfied: pycodestyle<2.6.0,>=2.5.0 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from flake8->-r requirements.txt (line 14)) (2.5.0)
Requirement already satisfied: mccabe<0.7.0,>=0.6.0 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from flake8->-r requirements.txt (line 14)) (0.6.1)
Requirement already satisfied: pyflakes<2.2.0,>=2.1.0 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from flake8->-r requirements.txt (line 14)) (2.1.1)
Requirement already satisfied: entrypoints<0.4.0,>=0.3.0 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from flake8->-r requirements.txt (line 14)) (0.3)
Requirement already satisfied: pytz in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from django<3.1,>=2.2->django-oscar<2.1,>=2.0->-r requirements.txt (line 2)) (2019.3)
Requirement already satisfied: Faker>=0.7.0 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from factory-boy<3.0,>=2.4.1->django-oscar<2.1,>=2.0->-r requirements.txt (line 2)) (4.0.0)
Requirement already satisfied: beautifulsoup4 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from webtest>=1.3.3->django-webtest==1.9.7->-r requirements.txt (line 4)) (4.8.2)
Requirement already satisfied: waitress>=0.8.5 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from webtest>=1.3.3->django-webtest==1.9.7->-r requirements.txt (line 4)) (1.4.3)
Requirement already satisfied: WebOb>=1.2 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from webtest>=1.3.3->django-webtest==1.9.7->-r requirements.txt (line 4)) (1.8.6)
Requirement already satisfied: distlib<1,>=0.3.0 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from virtualenv>=16.0.0->tox==3.14.5->-r requirements.txt (line 5)) (0.3.0)
Requirement already satisfied: appdirs<2,>=1.4.3 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from virtualenv>=16.0.0->tox==3.14.5->-r requirements.txt (line 5)) (1.4.3)
Requirement already satisfied: pyparsing>=2.0.2 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from packaging>=14->tox==3.14.5->-r requirements.txt (line 5)) (2.4.6)
Requirement already satisfied: zipp>=0.5 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from importlib-metadata<2,>=0.12; python_version < "3.8"->tox==3.14.5->-r requirements.txt (line 5)) (2.2.0)
Requirement already satisfied: wcwidth in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from pytest>=3.6->pytest-django==3.8.0->-r requirements.txt (line 6)) (0.1.8)
Requirement already satisfied: more-itertools>=4.0.0 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from pytest>=3.6->pytest-django==3.8.0->-r requirements.txt (line 6)) (8.2.0)
Requirement already satisfied: attrs>=17.4.0 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from pytest>=3.6->pytest-django==3.8.0->-r requirements.txt (line 6)) (19.3.0)
Requirement already satisfied: text-unidecode==1.3 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from Faker>=0.7.0->factory-boy<3.0,>=2.4.1->django-oscar<2.1,>=2.0->-r requirements.txt (line 2)) (1.3)
Requirement already satisfied: python-dateutil>=2.4 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from Faker>=0.7.0->factory-boy<3.0,>=2.4.1->django-oscar<2.1,>=2.0->-r requirements.txt (line 2)) (2.8.1)
Requirement already satisfied: soupsieve>=1.2 in /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages (from beautifulsoup4->webtest>=1.3.3->django-webtest==1.9.7->-r requirements.txt (line 4)) (2.0)
python setup.py develop
running develop
running egg_info
writing django_oscar_paypal.egg-info/PKG-INFO
writing dependency_links to django_oscar_paypal.egg-info/dependency_links.txt
writing requirements to django_oscar_paypal.egg-info/requires.txt
writing top-level names to django_oscar_paypal.egg-info/top_level.txt
reading manifest file 'django_oscar_paypal.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'django_oscar_paypal.egg-info/SOURCES.txt'
running build_ext
Creating /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages/django-oscar-paypal.egg-link (link to .)
django-oscar-paypal 2.0.0 is already the active version in easy-install.pth

Installed /home/appleyuchi/桌面/原始的Django-oscar/django-oscar-paypal
Processing dependencies for django-oscar-paypal==2.0.0
Searching for django-localflavor==3.0
Best match: django-localflavor 3.0
Adding django-localflavor 3.0 to easy-install.pth file

Using /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages
Searching for requests==2.22.0
Best match: requests 2.22.0
Adding requests 2.22.0 to easy-install.pth file

Using /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages
Searching for Django==2.2.10
Best match: Django 2.2.10
Adding Django 2.2.10 to easy-install.pth file
Installing django-admin script to /home/appleyuchi/.virtualenvs/python3.7/bin

Using /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages
Searching for python-stdnum==1.13
Best match: python-stdnum 1.13
Adding python-stdnum 1.13 to easy-install.pth file

Using /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages
Searching for certifi==2019.11.28
Best match: certifi 2019.11.28
Adding certifi 2019.11.28 to easy-install.pth file

Using /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages
Searching for chardet==3.0.4
Best match: chardet 3.0.4
Adding chardet 3.0.4 to easy-install.pth file
Installing chardetect script to /home/appleyuchi/.virtualenvs/python3.7/bin

Using /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages
Searching for idna==2.8
Best match: idna 2.8
Adding idna 2.8 to easy-install.pth file

Using /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages
Searching for urllib3==1.25.7
Best match: urllib3 1.25.7
Adding urllib3 1.25.7 to easy-install.pth file

Using /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages
Searching for pytz==2019.3
Best match: pytz 2019.3
Adding pytz 2019.3 to easy-install.pth file

Using /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages
Searching for sqlparse==0.3.0
Best match: sqlparse 0.3.0
Adding sqlparse 0.3.0 to easy-install.pth file
Installing sqlformat script to /home/appleyuchi/.virtualenvs/python3.7/bin

Using /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages
Finished processing dependencies for django-oscar-paypal==2.0.0
rm -f sandbox/db.sqlite
sandbox/manage.py migrate --noinput
Traceback (most recent call last):
  File "/home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages/django/apps/registry.py", line 155, in get_app_config
    return self.app_configs[app_label]
KeyError: 'communication'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sandbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/appleyuchi/桌面/原始的Django-oscar/django-oscar/src/oscar/apps/checkout/apps.py", line 18, in ready
    self.index_view = get_class('checkout.views', 'IndexView')
  File "/home/appleyuchi/桌面/原始的Django-oscar/django-oscar/src/oscar/core/loading.py", line 42, in get_class
    return get_classes(module_label, [classname], module_prefix)[0]
  File "/home/appleyuchi/桌面/原始的Django-oscar/django-oscar/src/oscar/core/loading.py", line 52, in get_classes
    return class_loader(module_label, classnames, module_prefix)
  File "/home/appleyuchi/桌面/原始的Django-oscar/django-oscar/src/oscar/core/loading.py", line 110, in default_class_loader
    oscar_module = _import_module(oscar_module_label, classnames)
  File "/home/appleyuchi/桌面/原始的Django-oscar/django-oscar/src/oscar/core/loading.py", line 144, in _import_module
    return __import__(module_label, fromlist=classnames)
  File "/home/appleyuchi/桌面/原始的Django-oscar/django-oscar/src/oscar/apps/checkout/views.py", line 17, in <module>
    = get_classes('checkout.forms', ['ShippingAddressForm', 'ShippingMethodForm', 'GatewayForm'])
  File "/home/appleyuchi/桌面/原始的Django-oscar/django-oscar/src/oscar/core/loading.py", line 52, in get_classes
    return class_loader(module_label, classnames, module_prefix)
  File "/home/appleyuchi/桌面/原始的Django-oscar/django-oscar/src/oscar/core/loading.py", line 110, in default_class_loader
    oscar_module = _import_module(oscar_module_label, classnames)
  File "/home/appleyuchi/桌面/原始的Django-oscar/django-oscar/src/oscar/core/loading.py", line 144, in _import_module
    return __import__(module_label, fromlist=classnames)
  File "/home/appleyuchi/桌面/原始的Django-oscar/django-oscar/src/oscar/apps/checkout/forms.py", line 5, in <module>
    from oscar.apps.customer.utils import normalise_email
  File "/home/appleyuchi/桌面/原始的Django-oscar/django-oscar/src/oscar/apps/customer/utils.py", line 8, in <module>
    Dispatcher = get_class('communication.utils', 'Dispatcher')
  File "/home/appleyuchi/桌面/原始的Django-oscar/django-oscar/src/oscar/core/loading.py", line 42, in get_class
    return get_classes(module_label, [classname], module_prefix)[0]
  File "/home/appleyuchi/桌面/原始的Django-oscar/django-oscar/src/oscar/core/loading.py", line 52, in get_classes
    return class_loader(module_label, classnames, module_prefix)
  File "/home/appleyuchi/桌面/原始的Django-oscar/django-oscar/src/oscar/core/loading.py", line 110, in default_class_loader
    oscar_module = _import_module(oscar_module_label, classnames)
  File "/home/appleyuchi/桌面/原始的Django-oscar/django-oscar/src/oscar/core/loading.py", line 144, in _import_module
    return __import__(module_label, fromlist=classnames)
  File "/home/appleyuchi/桌面/原始的Django-oscar/django-oscar/src/oscar/apps/communication/utils.py", line 9, in <module>
    CommunicationEventType = get_model('communication', 'CommunicationEventType')
  File "/home/appleyuchi/桌面/原始的Django-oscar/django-oscar/src/oscar/core/loading.py", line 248, in get_model
    return apps.get_model(app_label, model_name)
  File "/home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages/django/apps/registry.py", line 205, in get_model
    app_config = self.get_app_config(app_label)
  File "/home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages/django/apps/registry.py", line 162, in get_app_config
    raise LookupError(message)
LookupError: No installed app with label 'communication'.
make: *** [Makefile:11: sandbox] Error 1
(python3.7) appleyuchi@ubuntu19:django-oscar-paypal$ 

If I run:
`python sandbox/manage.py syncdb`
the same error happens.
Please help,Thanks~!

**Comment by solarissmoke** [comment]
I'm not able to reproduce this on a clean virtual environment on master - the sandbox builds just fine. Looking at your install log below it appears you're installing into a pre-existing virtual environment (hence all the `Requirement already satisfied` logs). I would suggest you try again in a fresh environment as most likely you have something in there that isn't right.

**Comment by appleyuchi** [comment]
> I'm not able to reproduce this on a clean virtual environment on master - the sandbox builds just fine. Looking at your install log below it appears you're installing into a pre-existing virtual environment (hence all the `Requirement already satisfied` logs). I would suggest you try again in a fresh environment as most likely you have something in there that isn't right.


I replicate a similar error with `djano-oscar`  when I `python sandbox/manage.py runserver` before `make sandbox`

So I guess:
the author of this repository run
 both  the"django-oscar-paypal" and "django-oscar" 
in only one environment.

**Comment by appleyuchi** [comment]
I have solved it.
