### ISSUE TITLE
conversion from NoneType to Decimal is not supported

### ISSUE THREAD

**Issue by ghost** [django-oscar/django-oscar-paypal#86]
The value of 'PAYMENTREQUEST_0_SHIPPINGAMT' is None, so converting to a Decimal is not possible:

https://github.com/django-oscar/django-oscar-paypal/blob/master/paypal/express/views.py#L361

You can see that 'PAYMENTREQUEST_0_SHIPPINGAMT' is never being set:

https://github.com/django-oscar/django-oscar-paypal/blob/master/paypal/express/gateway.py#L86

Is the value of

``` python
charge_incl_tax
```

meant to be

``` python
charge_incl_tax = self.txn.amount
```

instead?

**Comment by wingsaber** [comment]
it is not working whether you can change shpping charges or not. you have delete your python3.4 and download 2.7. I did that and worked

**Comment by anentropic** [comment]
I hit this issue... the problem is I had defined my shipping method to return a `Price` which only had `excl_tax` specified (as tax shouldn't be added to postage in UK)

Solution was to additionally specify `tax=D('0.00')`when returning the Price from `calculate` method
