### ISSUE TITLE
Broken link to Paypal website

### ISSUE THREAD

**Issue by dashmug** [django-oscar/django-oscar-paypal#90]
In the docs page at http://django-oscar-paypal.readthedocs.org/en/latest/payflow.html, there's a broken link pointing to https://merchant.paypal.com/us/cgi-bin/?cmd=_render-content&content_ID=merchant/payment_gateway.

Unfortunately, I couldn't find the right page that you are referring to so I cannot fix the doc page myself.

**Comment by smaggs** [comment]
According to archive.org, this URL went to an info page for PayFlow Payment Gateway until August 2012, when it began redirecting to a new info page for PayFlow and related offerings: https://www.paypal.com/webapps/mpp/payflow-payment-gateway

The new URL is working for me, so one could argue that this isn't broken, but it would also be OK to update the link to the new destination. It also might be handy to link to PayPal's developer docs for this feature: https://developer.paypal.com/docs/classic/products/payflow/
