### ISSUE TITLE
transaction_detail.html actions form visibility setting

### ISSUE THREAD

**Issue by armutcu** [django-oscar/django-oscar-paypal#93]
Firstly I don't know if this is the right place to post this as I am a newbie for web applications and github. Please warn me if I'm wrong...

Authorization setting is missing for transaction_detail.html actions form visibility which is set by
{% if show_forms %} 
or it should be show_form_buttons

**Comment by maikhoepfel** [comment]
Hi, welcome, and sorry for the late response :( I merged #94 now, so it should be fixed. Thanks for reporting and the fix!
