### ISSUE TITLE
PayPal Express redirect fails when using DeferredTax mixin

### ISSUE THREAD

**Issue by nfletton** [django-oscar/django-oscar-paypal#98]
The following error occurs when clicking the PayPal icon at the payment step of the checkout process when using the DeferredTax mixin:
```
Can't calculate price.incl_tax as tax isn't known
Request Method:	GET
Request URL:	http://127.0.0.1:5000/checkout/paypal/payment/
Django Version:	1.7.7
Exception Type:	TaxNotKnown
Exception Value:	Can't calculate price.incl_tax as tax isn't known
```

Bearing in mind this is the first time I've used Oscar, the problem appears to be that the PayPal Express RedirectView uses the basket in the request object rather than the basket after it has had tax applied by the the overridden build_submission() method in CheckoutSessionMixin.

The solution that works in my scenario is to call build_submission() directly to get the basket with deferred taxes calculated.

Old code:
```python
class RedirectView(CheckoutSessionMixin, RedirectView):
    ....
    def get_redirect_url(self, **kwargs):
        try:
            basket = self.request.basket
            url = self._get_redirect_url(basket, **kwargs)
        except PayPalError:
        ....
```

Patched code:
```python
class RedirectView(CheckoutSessionMixin, RedirectView):
    ....
    def get_redirect_url(self, **kwargs):
        try:
            basket = self.build_submission()['basket']
            url = self._get_redirect_url(basket, **kwargs)
        except PayPalError:
        ....
```

**Comment by taedori81** [comment]
I had same problem and tried your solution but, I got this error


TypeError at /checkout/paypal/redirect/

unorderable types: NoneType() > Decimal()

Request Method: 	GET
Request URL: 	http://0.0.0.0:8001/checkout/paypal/redirect/
Django Version: 	1.8.5
Exception Type: 	TypeError
Exception Value: 	

unorderable types: NoneType() > Decimal()

**Comment by fghaas** [comment]
Wow, I just wasted an entire day on this same exact problem, thinking something was wrong with my own CheckoutSessionMixin. @nfletton, thanks oodles for tracking it down. @maikhoepfel, it looks like this breaks pretty critical functionality -- any chance to get this issue reviewed?

**Comment by fghaas** [comment]
I've added PR #121 which implements @nfletton's suggested fix, which I can confirm fixes the problem for me — unfortunately I don't really know what would be a good way to unit-test this.

**Comment by calvinkcc** [comment]
Still a problem. Because using Express checkout means your not doing shipping parameters and when you don't do that means taxes isnt calculated. That's if your using an USstrategy. So what can we do about this situation?
