### ISSUE TITLE
Signature of Repository.get_shipping_methods

### ISSUE THREAD

**Issue by st8st8** [django-oscar/django-oscar-paypal#99]
Line 447 of paypal/express/views.py calls repo.get_shipping_methods with the signature:

    def get_shipping_methods(self, user, basket, shipping_address):
        repo = Repository()
        return repo.get_shipping_methods(
            user, basket, shipping_addr=shipping_address)

But in oscar/apps/shipping/repository.py it's given as:

    # API
    def get_shipping_methods(self, basket, shipping_addr=None, **kwargs):

ie with no "user" argument.  I'm not sure which is correct?

**Comment by maikhoepfel** [comment]
Good catch. The signature changed with Oscar 1.1. I'll have fix it and will issue a release no later than next week.

**Comment by maikhoepfel** [comment]
FYI, my work-in-progress branch is at #113.
